repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/timothycrosley/isort
    rev: 5.10.1  # pick the isort version you'd like to use from https://github.com/timothycrosley/isort/releases
    hooks:
    -   id: isort
-   repo: https://github.com/PyCQA/autoflake
    rev: v1.4
    hooks:
    -   id: autoflake
# -   repo: https://github.com/PyCQA/flake8
#     rev: 4.0.1
#     hooks:
#     -   id: flake8
-   repo: https://github.com/flakeheaven/flakeheaven
    rev: 0.11.0
    hooks:
    -   id: flakeheaven
# -   repo: https://github.com/python/mypy
#     rev: v0.942
#     hooks:
#     -   id: mypy
#         # verbose: true
#         # entry: bash -c 'mypy "$@" || true' --
