name: /home/ftorresd/projects/HZUpsilonPhotonRun2NanoAOD_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _sysroot_linux-64_curr_repodata_hack=3
  - abseil-cpp=20210324.2
  - afterimage=1.21
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=6.0.1
  - asttokens=2.0.5
  - astunparse=1.6.3
  - atk-1.0=2.36.0
  - attrs=21.4.0
  - awkward=1.8.0
  - awkward0=0.15.5
  - aws-c-auth=0.6.8
  - aws-c-cal=0.5.12
  - aws-c-common=0.6.17
  - aws-c-compression=0.2.14
  - aws-c-event-stream=0.2.7
  - aws-c-http=0.6.10
  - aws-c-io=0.10.14
  - aws-c-mqtt=0.7.10
  - aws-c-s3=0.1.29
  - aws-c-sdkutils=0.1.1
  - aws-checksums=0.1.12
  - aws-crt-cpp=0.17.10
  - aws-sdk-cpp=1.9.160
  - backcall=0.2.0
  - binutils=2.36.1
  - binutils_impl_linux-64=2.36.1
  - binutils_linux-64=2.36
  - black=22.3.0
  - bleach=4.1.0
  - boost-histogram=1.3.1
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - c-compiler=1.4.1
  - ca-certificates=2022.3.29
  - cachetools=5.0.0
  - cairo=1.16.0
  - certifi=2021.10.8
  - cffi=1.15.0
  - cfgv=3.3.1
  - cfitsio=4.0.0
  - charset-normalizer=2.0.12
  - click=8.0.4
  - cloudpickle=2.0.0
  - coffea=0.7.14
  - colorama=0.4.4
  - commonmark=0.9.1
  - compilers=1.4.1
  - conda=4.12.0
  - conda-package-handling=1.8.1
  - correctionlib=2.1.0
  - cryptography=36.0.2
  - cxx-compiler=1.4.1
  - cycler=0.11.0
  - dataclasses=0.8
  - davix=0.8.1
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecated=1.2.12
  - distlib=0.3.4
  - entrypoints=0.3
  - executing=0.8.3
  - expat=2.4.8
  - fftw=3.3.10
  - filelock=3.6.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.25.0
  - fortran-compiler=1.4.1
  - freetype=2.11.0
  - fribidi=1.0.10
  - fsspec=2022.3.0
  - ftgl=2.4.0
  - future=0.18.2
  - gcc=10.3.0
  - gcc_impl_linux-64=10.3.0
  - gcc_linux-64=10.3.0
  - gdk-pixbuf=2.42.8
  - gettext=0.21.0
  - gflags=2.2.2
  - gfortran=10.3.0
  - gfortran_impl_linux-64=10.3.0
  - gfortran_linux-64=10.3.0
  - giflib=5.2.1
  - gl2ps=1.4.2
  - glew=2.1.0
  - glog=0.5.0
  - graphite2=1.3.14
  - graphviz=2.50.0
  - grpc-cpp=1.42.0
  - gsl=2.7.1
  - gsoap=2.8.119
  - gtk2=2.24.33
  - gts=0.7.6
  - gxx=10.3.0
  - gxx_impl_linux-64=10.3.0
  - gxx_linux-64=10.3.0
  - harfbuzz=4.2.0
  - hepunits=2.2.0
  - hist=2.6.1
  - histoprint=2.2.1
  - icu=70.1
  - identify=2.4.12
  - idna=3.3
  - iminuit=2.8.4
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - importlib_resources=5.2.0
  - ipykernel=6.9.1
  - ipyparallel=6.3.0
  - ipython=8.2.0
  - ipython_genutils=0.2.0
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.0.3
  - jpeg=9e
  - jsonschema=3.2.0
  - jupyter_client=7.1.2
  - jupyter_core=4.9.2
  - jupyterlab_pygments=0.1.2
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libarchive=3.5.2
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.82.0
  - libcxx=12.0.1
  - libcxxabi=12.0.1
  - libdeflate=1.10
  - libedit=3.1.20210910
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-devel_linux-64=10.3.0
  - libgcc-ng=11.2.0
  - libgd=2.3.3
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.70.2
  - libglu=9.0.0
  - libgomp=11.2.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libllvm9=9.0.1
  - libmamba=0.22.1
  - libmambapy=0.22.1
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libopenblas=0.3.20
  - libpng=1.6.37
  - libprotobuf=3.19.4
  - librsvg=2.52.5
  - libsanitizer=10.3.0
  - libsodium=1.0.18
  - libsolv=0.7.22
  - libssh2=1.10.0
  - libstdcxx-devel_linux-64=10.3.0
  - libstdcxx-ng=11.2.0
  - libthrift=0.15.0
  - libtiff=4.3.0
  - libtool=2.4.6
  - libutf8proc=2.7.0
  - libuuid=2.32.1
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxml2=2.9.12
  - libzlib=1.2.11
  - llvmlite=0.38.0
  - lz4=3.1.3
  - lz4-c=1.9.3
  - lzo=2.10
  - mamba=0.22.1
  - markupsafe=2.0.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.2
  - metakernel=0.27.5
  - mistune=0.8.4
  - mplhep=0.3.23
  - mplhep_data=0.0.3
  - munkres=1.1.4
  - mypy=0.910
  - mypy_extensions=0.4.3
  - nbclient=0.5.11
  - nbconvert=6.3.0
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.1
  - nlohmann_json=3.10.5
  - nodeenv=1.6.0
  - notebook=6.4.8
  - numba=0.55.1
  - numpy=1.21.5
  - openssl=1.1.1n
  - orc=1.7.1
  - packaging=21.3
  - pandas=1.4.2
  - pandocfilters=1.5.0
  - pango=1.50.6
  - parquet-cpp=1.5.1
  - parso=0.8.3
  - particle=0.20.1
  - pathspec=0.9.0
  - pcre=8.45
  - pdoc=11.1.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=21.2.4
  - pixman=0.40.0
  - platformdirs=2.4.0
  - plotext=4.2.0
  - portalocker=2.3.0
  - pre-commit=2.18.1
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=6.0.1
  - pybind11-abi=4
  - pycosat=0.6.3
  - pycparser=2.21
  - pydantic=1.9.0
  - pygments=2.12.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - pythia8=8.305
  - python=3.9.12
  - python-dateutil=2.8.2
  - python-xxhash=2.0.2
  - python_abi=3.9
  - pytz=2022.1
  - pyyaml=6.0
  - pyzmq=22.3.0
  - re2=2021.11.01
  - readline=8.1.2
  - reproc=14.2.3
  - reproc-cpp=14.2.3
  - requests=2.27.1
  - rich=12.2.0
  - root=6.26.0
  - root_base=6.26.0
  - ruamel_yaml=0.15.80
  - s2n=1.3.0
  - scipy=1.8.0
  - scitokens-cpp=0.6.3
  - send2trash=1.8.0
  - setuptools=58.0.4
  - shellingham=1.3.1
  - six=1.16.0
  - snappy=1.1.8
  - sqlite=3.38.2
  - stack_data=0.2.0
  - sysroot_linux-64=2.17
  - tbb=2021.5.0
  - terminado=0.13.1
  - testpath=0.5.0
  - textual=0.1.17
  - tk=8.6.12
  - toml=0.10.2
  - tomli=1.2.2
  - tornado=6.1
  - tqdm=4.63.0
  - traitlets=5.1.1
  - typed-ast=1.4.3
  - typer=0.4.1
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - tzdata=2022a
  - uhi=0.3.1
  - ukkonen=1.0.1
  - uproot=4.2.2
  - uproot-base=4.2.2
  - uproot-browser=0.4.0
  - uproot3=3.14.4
  - uproot3-methods=0.10.1
  - urllib3=1.26.9
  - vdt=0.4.3
  - vector-classes=1.4.2
  - virtualenv=20.14.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - wrapt=1.13.3
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxcursor=1.2.0
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxft=2.3.4
  - xorg-libxpm=3.5.13
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xrootd=5.4.1
  - xxhash=0.8.0
  - xz=5.2.5
  - yaml=0.2.5
  - yaml-cpp=0.6.3
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.11
  - zstandard=0.15.2
  - zstd=1.5.2
