[tool.isort]
profile = "black"
known_third_party = ["awkward", "coffea", "numpy", "particle", "tqdm", "typer", "uproot"]

[tool.flakeheaven]
# optionally inherit from remote config (or local if you want)
base = "https://raw.githubusercontent.com/flakeheaven/flakeheaven/main/pyproject.toml"
# make output nice
format = "grouped"
# don't limit yourself
max_line_length = 600
# show line of source code in output
show_source = true

[tool.flakeheaven.plugins]
pycodestyle = ["+*", "-W503"]
pyflakes = ["+*"]

[mypy]
plugins = ["numpy.typing.mypy_plugin"]
warn_unused_configs = true
warn_unused_ignores = true
python_version = "3.9"
strict = true
show_error_codes = true
warn_unreachable = true
enable_error_code = ["ignore-without-code", "redundant-expr", "truthy-bool"]
